### PR TITLE
Ci linting

### PR DESCRIPTION
**Pull request by mira-t**
We want to use continuous integration with Monster UI. Part of this is to maintain code quality through use of a linter. The first module we have attempted this with is Webhooks and we would appreciate your feedback. As a start, we have:

1. Created an eslint configuration file that conforms to the styleguides. This can be used in conjunction with Circle CI (or any other CI tool). A Circle CI configuration file has been included.

2. Using the linter, updated the Webhooks git submodule to conform to the styleguides (general and javascript) where possible (exceptions listed below).

- The 2600Hz Javascript Style Guide states that variable names should be camel case. However, snake case is sometimes required in the existing code.
- "===" and "!==" should be used instead of "==" and "!=". However, there is some intentional use of "==" and "!=" in the rest of Monster UI, so this rule is turned off.
- Enforcing that the variable declarations are at the top of their scope can introduce errors as it needs to be resolved manually. Therefore, this rule is not enforced (vars-on-top).
- Redeclaring a variable is not allowed but this rule is commonly broken in Monster when the parameter to a function is redefined inside the function. A custom rule could be made in future to allow for this.

### CODE REVIEW

**Comment by JRMaitre** [comment]
Hello, we started using a .jshintrc to lint the code. We also added a gulp lint task to show errors, and if you uncomment it you can get errors on build (although it doesn't output it on live refresh, we have to add that).

Please use that jshintrc file or submit a pull request to change some settings that you'd prefer so we can talk about them.

About camelcase, we have a weird convention for that one, we use camelCase in javascript but use the underscore notation for everything that comes from the back-end, since it's already using underscores everywhere.

All the other fields shouldn't have underscore in them.

For the CSS it's a little different and it's even more chaotic, but we mostly use dashes for class names, and _ for IDs.

**Comment by JRMaitre** [comment]
I should say that our jshint file right now is still a work in progress, we started really looking at it last week because we want to use it during our build, and also to allow plugins like SublimeLinter etc... to work with it. It's possible there's some settings in there that don't match what is describe in our coding guideline, and we're looking to fix that, so if you see inconsistencies, you should definitely point it out.

There's also definitely a lot of "errors" and "warnings" reported by jshint that haven't been fixed in the code because we haven't really started linting our code based on the jshint reports. We're looking to do that as a work in progress, as we come across different files in the code.

We're definitely open to feedback and willing to change our process since it's very much in construction right now, so happy to discuss anything :)

One thing I would say is that we'd want to use the same configuration across all modules and apps in the repo, so the file would be stored in src/ and not on an app basis like in this commit.

Thanks a lot for your pull-request and looking forward to talk more about it :)

**Comment by JRMaitre** [comment]
Now that I've had more time to think about it, I think I want to look more into eslint because from what I've seen it might be a little more dev-friendly than jslint.

I created a ticket for myself and I'll look at this when I'm done with my current project (should be able to look at it sometimes next week)

**Comment by mira-t** [comment]
Because Circle CI is the continuous integration for Kazoo 4.0, we thought it would be a good idea to use it for Monster as well. My understanding is that Circle CI runs builds/tests per repository. Therefore, our plans are to include an eslint config file and Circle CI config file at the top level of each of the Monster repositories. This is our reason for including the eslint config and circle CI config in webhooks, as opposed to only inside the src folder.

Thank you very much for your feedback, we look forward to your response later this week.

**Comment by JRMaitre** [comment]
You're right, we should be consistent and use the same tools across our different projects. However, we haven't been using it for the UI. I will look into it and check back later this week or the next one, a little busy right now :)

**Comment by JRMaitre** [comment]
After looking into it, I'll merge it :) 

Thanks a LOT for this!

The eslint config file is really well done and I'm happy with the errors we get out of it. I added it to the main monster-ui folder too just so we can see the errors when using our code editor. I had to remove the linebreak rule because for developers on windows it's just too much work to fix elegantly. But besides that, it looks great to me. I can't wait to start fixing a lot of these files.

**Pull request merged**
